### ISSUE TITLE
Crash on data update

### ISSUE THREAD

**Issue by richardmansfield** [jordan-thoms/2Degrees-Toolbox#10]
Since about 13 Feb, the app has crashed for me every time it tries to update. It also happens to a friend of mine, and it seems a few recent commenters over at google play have the same problem. Some logcat messages:

```
02-28 20:56:35.683  4739  4796 I ActivityManager: Start proc 31854:biz.shadowservices.DegreesToolbox/u0a67 for broadcast biz.shadowservices.DegreesToolbox/.UpdateReciever
02-28 20:56:36.814  4739 23894 D ConnectivityService: Returning unblocked NetworkInfo to uid=10067
02-28 20:56:37.874  4739  4784 I ActivityManager: Start proc 31876:biz.shadowservices.DegreesToolbox:exceptionReporter/u0a67 for service biz.shadowservices.DegreesToolbox/de.quist.app.errorreporter.ExceptionReportService
02-28 20:56:37.876 31854 31871 E AndroidRuntime: FATAL EXCEPTION: Thread-1
02-28 20:56:37.876 31854 31871 E AndroidRuntime: Process: biz.shadowservices.DegreesToolbox, PID: 31854
02-28 20:56:37.876 31854 31871 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
02-28 20:56:37.876 31854 31871 E AndroidRuntime:        at biz.shadowservices.DegreesToolbox.DataFetcher.updateData(DataFetcher.java:193)
02-28 20:56:37.876 31854 31871 E AndroidRuntime:        at biz.shadowservices.DegreesToolbox.UpdateWidgetService.run(UpdateWidgetService.java:117)
02-28 20:56:37.876 31854 31871 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)

02-28 21:57:21.940  4739  5193 I ActivityManager: Start proc 4166:biz.shadowservices.DegreesToolbox:exceptionReporter/u0a67 for service biz.shadowservices.DegreesToolbox/de.quist.app.errorreporter.ExceptionReportService
02-28 21:57:21.943  4135  4163 E AndroidRuntime: FATAL EXCEPTION: Thread-1
02-28 21:57:21.943  4135  4163 E AndroidRuntime: Process: biz.shadowservices.DegreesToolbox, PID: 4135
02-28 21:57:21.943  4135  4163 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
02-28 21:57:21.943  4135  4163 E AndroidRuntime: 	at biz.shadowservices.DegreesToolbox.DataFetcher.updateData(DataFetcher.java:193)
02-28 21:57:21.943  4135  4163 E AndroidRuntime: 	at biz.shadowservices.DegreesToolbox.UpdateWidgetService.run(UpdateWidgetService.java:117)
02-28 21:57:21.943  4135  4163 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-28 21:57:21.946  4739  8265 W ActivityManager:   Force finishing activity biz.shadowservices.DegreesToolbox/.MainActivity
```

**Comment by MadAsKiwi** [comment]
Sorry for speaking out of turn, but I would say that this is directly related to the system failures at 2dm.

Jordan, if you are still developing this app, if possible, could you add a timeout that stops the app from trying to contact the 2dm system to try and stop this from happening?  If you need a tester (once 2dm's systems are back up), please let me know and I will be happy to help
